---
AWSTemplateFormatVersion: '2010-09-09'
Description: Snyk integration for AWS Lambda with Serverless CICD Child Accounts. (qs-1qqfh4fnp)
Outputs:
  SnykLambdaIntegrationRole:
    Description: Snyk Lambda Integration Role ARN
    Value: !GetAtt 'LambdaIntegrationStack.Outputs.SnykLambdaIntegrationRole'
  Version:
    Description: Snyk Lambda Integration Version
    Value: 1.0.2
  CCIDRemoteAccountRole:
    Description: Trek10 CICD IAM Integration Role ARN
    Value: !GetAtt 'CICDChildStack.Outputs.RemoteAccountRole'
  CCIDRemoteAccountRoleName:
    Description: Trek10 CICD IAM Integration Role Name
    Value: !GetAtt 'CICDChildStack.Outputs.RemoteAccountRoleName'
Metadata:
  LICENSE: Apache License, Version 2.0
  QuickStartDocumentation:
    EntrypointName: "Snyk integration for AWS Lambda with Serverless CICD Child Accounts"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Snyk configuration
        Parameters:
          - SnykExternalId
      - Label:
          default: Trek10 Serverless CICD
        Parameters:
          - CentralAwsAccountId
          - ChildAccountRoleName
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels:
      CentralAwsAccountId:
        default: Shared services account ID
      ChildAccountRoleName:
        default: Child account role name
      SnykExternalId:
        default: Snyk organization ID
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
Parameters:
  CentralAwsAccountId:
    Description: The AWS account ID of the shared services account. For guidance, see Finding Your AWS Account ID in the AWS documentation.
    Type: String
    AllowedPattern: (\d{12}|^$)
    ConstraintDescription: Must be an AWS account ID
  ChildAccountRoleName:
    Description: The name of the role to create in the account. This name must be unique in the account.
    Default: ChildAccountRole
    Type: String
  SnykExternalId:
    Description: You may find this by logging in to https://app.snyk.io and navigate to Settings.
    Type: String
    AllowedPattern: '[a-z0-9-]{36}'
    MinLength: 1
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription:
      Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description:
      S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription:
      Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots (.), and forward slash (/).
    Default: quickstart-snyk-serverless/
    Description:
      S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String
Conditions:
  UsingDefaultBucket: !Equals
    - !Ref QSS3BucketName
    - 'aws-quickstart'
Resources:
  CICDChildStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        CentralAwsAccountId: !Ref 'CentralAwsAccountId'
        ChildAccountRoleName: !Ref 'ChildAccountRoleName'
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-trek10-serverless-enterprise-cicd/ChildAccountRole.template.yaml'
        - S3Bucket: !If
            - UsingDefaultBucket
            - !Sub 'aws-quickstart-${AWS::Region}'
            - !Ref 'QSS3BucketName'
          S3Region: !If
            - UsingDefaultBucket
            - !Ref 'AWS::Region'
            - !Ref 'QSS3BucketRegion'
  LambdaIntegrationStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        SnykExternalId: !Ref 'SnykExternalId'
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-snyk-security/templates/snyk-lambda.template.yaml'
        - S3Bucket: !If
            - UsingDefaultBucket
            - !Sub 'aws-quickstart-${AWS::Region}'
            - !Ref 'QSS3BucketName'
          S3Region: !If
            - UsingDefaultBucket
            - !Ref 'AWS::Region'
            - !Ref 'QSS3BucketRegion'
